name: AppRTCMobile
options:
  bundleIdPrefix: com.github.otmb
targets:
  AppRTCMobile:
    type: application
    platform: iOS
    deploymentTarget: "11.3"
    sources:
      - path: AppRTCMobile
        excludes:
          - "tests/*.*"
          - "mac/*.*"
    settings:
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      INFOPLIST_FILE: "AppRTCMobile/ios/Info.plist"
      ENABLE_BITCODE: "NO"
      OTHER_LDFLAGS: "$(inherited) -licucore"
